apiVersion: v1
appVersion: "v2.2.0.beta10"
description: A platform for community discussion. Free, open, simple.
name: discourse
version: 0.2.0
home: https://www.discourse.org
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
